import type { Product, Store, Recipe } from "./types"

export const mockStores: Store[] = [
  {
    id: "1",
    name: "SuperMercado Fresh",
    logo: "🛒",
    rating: 4.5,
    deliveryTime: "30-45 min",
  },
  {
    id: "2",
    name: "Mercado do Bairro",
    logo: "🏪",
    rating: 4.2,
    deliveryTime: "45-60 min",
  },
  {
    id: "3",
    name: "Atacadão Plus",
    logo: "🏬",
    rating: 4.0,
    deliveryTime: "60-90 min",
  },
]

export const mockProducts: Product[] = [
  // SuperMercado Fresh
  {
    id: "1",
    name: "Macarrão Espaguete",
    description: "Macarrão espaguete 500g",
    price: 4.5,
    unit: "pacote",
    category: "Massas",
    store: mockStores[0],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "2",
    name: "Carne Moída",
    description: "Carne moída bovina 1kg",
    price: 22.9,
    unit: "kg",
    category: "Carnes",
    store: mockStores[0],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "3",
    name: "Molho de Tomate",
    description: "Molho de tomate tradicional 340g",
    price: 3.2,
    unit: "lata",
    category: "Molhos",
    store: mockStores[0],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  // Mercado do Bairro
  {
    id: "4",
    name: "Macarrão Espaguete",
    description: "Macarrão espaguete 500g",
    price: 4.8,
    unit: "pacote",
    category: "Massas",
    store: mockStores[1],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "5",
    name: "Carne Moída",
    description: "Carne moída bovina 1kg",
    price: 21.5,
    unit: "kg",
    category: "Carnes",
    store: mockStores[1],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "6",
    name: "Molho de Tomate",
    description: "Molho de tomate tradicional 340g",
    price: 2.9,
    unit: "lata",
    category: "Molhos",
    store: mockStores[1],
    image: "/placeholder.svg?height=100&width=100",
    inStock: false,
  },
  // Atacadão Plus
  {
    id: "7",
    name: "Macarrão Espaguete",
    description: "Macarrão espaguete 500g",
    price: 4.2,
    unit: "pacote",
    category: "Massas",
    store: mockStores[2],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "8",
    name: "Carne Moída",
    description: "Carne moída bovina 1kg",
    price: 23.5,
    unit: "kg",
    category: "Carnes",
    store: mockStores[2],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "9",
    name: "Molho de Tomate",
    description: "Molho de tomate tradicional 340g",
    price: 3.5,
    unit: "lata",
    category: "Molhos",
    store: mockStores[2],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
]

export const popularRecipes: Recipe[] = [
  {
    id: "popular-1",
    title: "Macarrão à Bolonhesa",
    description: "Clássico macarrão com molho de carne",
    ingredients: ["Macarrão Espaguete", "Carne Moída", "Molho de Tomate", "Cebola", "Alho"],
    instructions: [
      "Cozinhe o macarrão em água fervente com sal",
      "Refogue a cebola e alho",
      "Adicione a carne moída e cozinhe",
      "Acrescente o molho de tomate",
      "Misture com o macarrão e sirva",
    ],
    servings: 4,
    prepTime: "30 min",
    difficulty: "easy",
    isPersonal: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "popular-2",
    title: "Risotto de Cogumelos",
    description: "Cremoso risotto italiano",
    ingredients: ["Arroz Arbóreo", "Cogumelos", "Caldo de Legumes", "Vinho Branco", "Queijo Parmesão"],
    instructions: [
      "Refogue os cogumelos",
      "Adicione o arroz e torre levemente",
      "Acrescente o vinho branco",
      "Adicione o caldo aos poucos",
      "Finalize com queijo parmesão",
    ],
    servings: 3,
    prepTime: "45 min",
    difficulty: "medium",
    isPersonal: false,
    createdAt: new Date("2024-01-02"),
  },
]
